@echo off
rem DEVTOOL_WRAPPER_LAUNCHER=1
rem Generated by `devtool wrapper init/update`. Do not edit by hand.
setlocal
set "DEVTOOL_REPO_ROOT=%~dp0"
if "%DEVTOOL_REPO_ROOT:~-1%"=="\" set "DEVTOOL_REPO_ROOT=%DEVTOOL_REPO_ROOT:~0,-1%"

if not "%DEVTOOL_WRAPPER_EXECUTABLE%"=="" (
  if not exist "%DEVTOOL_WRAPPER_EXECUTABLE%" (
    echo DEVTOOL_WRAPPER_RUNTIME_MISSING: executable does not exist: %DEVTOOL_WRAPPER_EXECUTABLE% 1>&2
    exit /b 127
  )
  "%DEVTOOL_WRAPPER_EXECUTABLE%" --repo "%DEVTOOL_REPO_ROOT%" wrapper exec %*
  exit /b %ERRORLEVEL%
)

if exist "%DEVTOOL_REPO_ROOT%\devtool\__main__.py" if exist "%DEVTOOL_REPO_ROOT%\pyproject.toml" (
  if not "%DEVTOOL_WRAPPER_PYTHON%"=="" (
    set "PYTHONPATH=%DEVTOOL_REPO_ROOT%;%PYTHONPATH%"
    "%DEVTOOL_WRAPPER_PYTHON%" -m devtool --repo "%DEVTOOL_REPO_ROOT%" wrapper exec %*
    exit /b %ERRORLEVEL%
  )
  where python >nul 2>nul
  if not errorlevel 1 (
    set "PYTHONPATH=%DEVTOOL_REPO_ROOT%;%PYTHONPATH%"
    python -m devtool --repo "%DEVTOOL_REPO_ROOT%" wrapper exec %*
    exit /b %ERRORLEVEL%
  )
)

where devtool >nul 2>nul
if errorlevel 1 (
  echo DEVTOOL_WRAPPER_RUNTIME_MISSING: no Devtool runtime was found ^(override, source runtime, or PATH^). 1>&2
  exit /b 127
)
devtool --repo "%DEVTOOL_REPO_ROOT%" wrapper exec %*
exit /b %ERRORLEVEL%
